# Generated by Django 4.0.1 on 2022-02-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaflix', '0003_movie_actors_movie_categories_movie_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
