# Generated by Django 4.0.1 on 2022-03-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaflix', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[['male', 'Muž'], ['female', 'Žena'], ['other', 'Jiné']], default='male', max_length=32),
        ),
    ]
