# Generated by Django 4.0.1 on 2022-04-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaflix', '0005_alter_actor_options_actor_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Nahled'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Video soubor'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[('male', 'Muž'), ('female', 'Žena'), ('other', 'Ostatní')], default='male', max_length=32),
        ),
    ]
